---
- hosts: webservers
  become: yes
  gather_facts: false
  tasks:
    - name: install packages
      yum:
        name: "{{ item }}"
        state: present
   #    with_items:
      loop:
        - curl
        - finger
        - wget
        - httpd
        - ntp
