---
- hosts: webservers
  become: yes
  ignore_errors: yes
  gather_facts: 1
  tasks:
    - name: check number of cpu 
      command: nproc 
      register: nproc_output 

    - name: Display the output
      debug:
        var: nproc_output
    - name: create file
      file:
        path: /homr/ec2-user/week3
        state: touch
        mode: '0644
    
